# Generated by Django 3.2.9 on 2021-11-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_empmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpModel',
        ),
    ]
